// app/layout.tsx
import type { Metadata } from 'next';
import Providers from './providers';
import './globals.css';
import ThemeController from '@/components/theme-controller';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <header>
            <nav>
              {/*... 네비게이션... */}
              <ThemeController />
            </nav>
          </header>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
