CREATE TABLE public.posts (
  -- 자동 증가하는 bigint 타입의 기본 키
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- 게시물을 작성한 사용자의 id, profiles 테이블의 id를 참조
  user_id uuid NOT NULL,
  -- 게시물 제목
  title text NOT NULL,
  -- 게시물 내용
  content text,
  -- 생성 시각은 기본값으로 현재 시각(UTC)이 저장됨
  created_at timestamptz DEFAULT now() NOT NULL,

  -- user_id가 profiles.id를 참조하도록 외래 키 설정
  -- 부모 레코드(profile) 삭제 시 관련된 자식 레코드(post)도 함께 삭제 (ON DELETE CASCADE)
  CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON DELETE CASCADE
);
